### ISSUE TITLE
Craft 4 Compatibility?

### ISSUE THREAD

**Issue by joelzerner** [clearbold/craft-campaignmonitor-service#4]
Firstly - thanks for this super handy Craft plugin. Appreciate your work!

Secondly - wondering if it will be upgraded to be compatible with Craft 4 in the near future and if so, what the timeline would be? If not, then we'll need to figure out an alternative method to achieve the same functionality.

**Comment by heymarkreeves** [comment]
Hi, @joelzerner! Thanks for reaching out. I started taking a look at this. Are you just using this plugin? Or are you using **craft-campaignmonitor-transactional** or **craft-campaignmonitor-lists**, too.

I'm trying to figure out how to fit in this work and this plugin—the service—is really just a wrapper to the Campaign Monitor PHP library.

Thanks!

**Comment by joelzerner** [comment]
We're just using this plugin at the moment.

That's true - so if you're not planning on bringing it across to Craft 4 for the moment, we'll probably just set up the CM PHP library and hook into that directly via our default site module.

**Comment by heymarkreeves** [comment]
@joelzerner, I won't rule out migrating this to Craft 4, but for the needs you described, I think leveraging the CM PHP library in your module makes sense. You can use the wrapper methods in this plugin as a starting point.

The real goal of this one was to provide the common underpinnings for the CM Transactional and CM Lists plugins, which assumed someone was using CM for email campaigns already and wanted to leverage their account for transactional email, too. I'd be curious as to what the demand is for that approach at this point, as it seems there are more compelling options than CM now. (CM seems to have languished after the founders sold it.)

**Comment by joelzerner** [comment]
@heymarkreeves I was just reminded that we do have another project which uses the transactional plugin and the service plugin. Maybe I'm one the key users of these plugins!? Do you have stats on the usage?

Anyway, for now I'll continue under the assumption that you're not porting these to Craft 4 in the short-term. I'm not sure how we'll tackle the project that uses the transactional plugin but I'll consider adapting it (if it's not beyond me) or finding another way.

**Comment by heymarkreeves** [comment]
@joelzerner, it looks like there are 33 installs of transactional, vs 3,593 for the Postmark adapter (which is what I typically use); 1,329 for Amazon SES; 2,324 for SendGrid; 4,228 for Mailgun, and only 76 for Mailchimp.

That said, I do have one site that uses these plugins, too, as I'm sending notification emails and adding prospects to CM lists, and I'm migrating that site to a new Craft 4 install this year. If we're sticking with CM for subscriber lists and email campaigns, I may be updating these then. Though I might just switch them to Postmark and use the CM PHP library to add subscribers.
